'use client'

import { useState, useEffect } from 'react'

export default function TestFlipbookPage() {
  const [running, setRunning] = useState(false)
  const [elapsed, setElapsed] = useState(0)
  const [selectedScene, setSelectedScene] = useState(0)
  const [result, setResult] = useState<any>(null)

  useEffect(() => {
    if (!running) return
    const timer = setInterval(() => setElapsed(prev => prev + 1), 1000)
    return () => clearInterval(timer)
  }, [running])

  async function runTest() {
    setRunning(true)
    setElapsed(0)
    setResult(null)
    try {
      const res = await fetch('/api/test-flipbook', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ scene: selectedScene }),
      })
      const data = await res.json()
      setResult(data)
    } catch (err) {
      setResult({ error: err instanceof Error ? err.message : 'Failed' })
    }
    setRunning(false)
  }

  const sceneOptions = [
    { value: 0, label: 'Protection Story', desc: 'Storm → golden shield protects family → sunshine (6 frames)', icon: '🛡️' },
    { value: 1, label: 'Growth Garden', desc: 'Seed planted → sprout → tree → magnificent oak with family (6 frames)', icon: '🌳' },
    { value: 2, label: 'Both scenes combined', desc: 'Full 2-scene flipbook video (12 frames total)', icon: '🎬' },
  ]

  return (
    <div style={{ minHeight: '100vh', background: '#F4F1EC', padding: 32, fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 4 }}>Flipbook Animation Test</h1>
        <p style={{ fontSize: 14, color: '#8A968D', marginBottom: 4 }}>
          Illustrated scenes with progressive frames — each frame generated by Gemini, assembled into a flipbook-style animation with narration.
        </p>
        <p style={{ fontSize: 12, color: '#8A968D', marginBottom: 32 }}>
          No AI video models. Just sequential images + FFmpeg frame blending + TTS audio.
        </p>

        {/* Scene selector */}
        {!running && !result && (
          <>
            <div style={{ marginBottom: 24 }}>
              <label style={{ fontSize: 13, fontWeight: 700, display: 'block', marginBottom: 10 }}>Choose a test scene</label>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {sceneOptions.map(opt => (
                  <button
                    key={opt.value}
                    onClick={() => setSelectedScene(opt.value)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: 14,
                      padding: '16px 20px', borderRadius: 10, textAlign: 'left',
                      border: selectedScene === opt.value ? '2px solid #6FA13A' : '2px solid #E5DFD3',
                      background: selectedScene === opt.value ? 'rgba(199,232,168,0.1)' : 'white',
                      cursor: 'pointer',
                    }}
                  >
                    <span style={{ fontSize: 28 }}>{opt.icon}</span>
                    <div>
                      <div style={{ fontWeight: 700, fontSize: 15 }}>{opt.label}</div>
                      <div style={{ fontSize: 12, color: '#8A968D', marginTop: 2 }}>{opt.desc}</div>
                    </div>
                  </button>
                ))}
              </div>
            </div>

            <div style={{ display: 'flex', gap: 16, alignItems: 'center', marginBottom: 24 }}>
              <button onClick={runTest} style={{
                padding: '16px 40px', borderRadius: 10, border: 'none',
                background: '#0F1A12', color: '#C7E8A8', fontSize: 16, fontWeight: 700, cursor: 'pointer',
              }}>
                Generate Flipbook &rarr;
              </button>
              <div style={{ fontSize: 12, color: '#8A968D' }}>
                Est. cost: ~${selectedScene === 2 ? '0.46' : '0.28'} &middot; Time: {selectedScene === 2 ? '3-5' : '2-3'} min
              </div>
            </div>
          </>
        )}

        {running && (
          <div style={{ background: 'white', borderRadius: 10, border: '1px solid #E5DFD3', padding: 32 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 20 }}>
              <div style={{ width: 32, height: 32, border: '3px solid #C7E8A8', borderTopColor: 'transparent', borderRadius: '50%', animation: 'spin 1s linear infinite' }} />
              <div>
                <div style={{ fontSize: 18, fontWeight: 700 }}>Creating flipbook animation...</div>
                <div style={{ fontSize: 14, color: '#8A968D' }}>
                  {Math.floor(elapsed / 60)}:{(elapsed % 60).toString().padStart(2, '0')} elapsed
                </div>
              </div>
            </div>
            <div style={{ fontSize: 13, color: '#4B574F' }}>
              {elapsed < 5 && <p>Generating narration voice...</p>}
              {elapsed >= 5 && elapsed < 20 && <p>Generating frame 1 — setting the scene...</p>}
              {elapsed >= 20 && elapsed < 40 && <p>Generating frame 2-3 — building the story...</p>}
              {elapsed >= 40 && elapsed < 80 && <p>Generating frames 4-5 — the dramatic reveal...</p>}
              {elapsed >= 80 && elapsed < 120 && <p>Generating final frame — the resolution...</p>}
              {elapsed >= 120 && elapsed < 150 && <p>Assembling flipbook with frame blending...</p>}
              {elapsed >= 150 && <p>Uploading final video...</p>}
            </div>
            <div style={{ marginTop: 16, height: 6, background: '#E5DFD3', borderRadius: 3, overflow: 'hidden' }}>
              <div style={{
                height: '100%', background: '#C7E8A8', borderRadius: 3,
                transition: 'width 2s ease',
                width: elapsed < 5 ? '5%' : elapsed < 40 ? '25%' : elapsed < 80 ? '50%' : elapsed < 120 ? '75%' : elapsed < 150 ? '90%' : '95%',
              }} />
            </div>
          </div>
        )}

        {result && (
          <div style={{ background: 'white', borderRadius: 10, border: '1px solid #E5DFD3', overflow: 'hidden' }}>
            {result.error ? (
              <div style={{ padding: 24 }}>
                <div style={{ color: '#b91c1c', fontWeight: 700, marginBottom: 8 }}>Error</div>
                <div style={{ fontSize: 13, marginBottom: 16 }}>{result.error}</div>
                {result.log && (
                  <details>
                    <summary style={{ cursor: 'pointer', fontSize: 13, color: '#8A968D' }}>Show log</summary>
                    <pre style={{ fontSize: 11, background: '#F4F1EC', padding: 12, borderRadius: 8, overflow: 'auto', maxHeight: 300, marginTop: 8 }}>
                      {result.log.join('\n')}
                    </pre>
                  </details>
                )}
                <button onClick={() => setResult(null)} style={{ marginTop: 12, padding: '10px 20px', borderRadius: 10, border: '1px solid #E5DFD3', background: 'white', cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                  Try Again
                </button>
              </div>
            ) : (
              <>
                <video src={result.videoUrl} controls autoPlay style={{ width: '100%', display: 'block' }} />
                <div style={{ padding: 20 }}>
                  <div style={{ fontSize: 16, fontWeight: 700, marginBottom: 4 }}>
                    Flipbook generated in {Math.floor(result.totalTime / 60)}:{(result.totalTime % 60).toString().padStart(2, '0')}
                  </div>
                  <div style={{ fontSize: 13, color: '#8A968D', marginBottom: 4 }}>
                    {result.totalFrames} frames &middot; Cost: {result.cost} &middot; No AI video models used
                  </div>
                  <div style={{ fontSize: 12, color: '#8A968D', marginBottom: 16 }}>
                    Scenes: {result.scenes?.join(' + ')}
                  </div>
                  <div style={{ display: 'flex', gap: 10 }}>
                    <a href={result.videoUrl} download target="_blank" rel="noopener noreferrer"
                      style={{ padding: '10px 20px', borderRadius: 10, background: '#0F1A12', color: '#C7E8A8', fontSize: 13, fontWeight: 700, textDecoration: 'none' }}>
                      Download MP4
                    </a>
                    <button onClick={() => setResult(null)} style={{ padding: '10px 20px', borderRadius: 10, border: '1px solid #E5DFD3', background: 'white', cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                      Try Another Scene
                    </button>
                  </div>
                  {result.log && (
                    <details style={{ marginTop: 16 }}>
                      <summary style={{ cursor: 'pointer', fontSize: 13, color: '#8A968D' }}>Show generation log</summary>
                      <pre style={{ fontSize: 11, background: '#F4F1EC', padding: 12, borderRadius: 8, overflow: 'auto', maxHeight: 300, marginTop: 8 }}>
                        {result.log.join('\n')}
                      </pre>
                    </details>
                  )}
                </div>
              </>
            )}
          </div>
        )}

        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    </div>
  )
}
