import { NextResponse } from 'next/server'
import { createClient } from '../../_lib/supabase/server'
import OpenAI from 'openai'
import { GoogleGenAI } from '@google/genai'

export const runtime = 'nodejs'
export const maxDuration = 120

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })

  const { logoImage, prompt, companyName, provider = 'openai' } = await request.json() as {
    logoImage?: string
    prompt: string
    companyName?: string
    provider?: 'openai' | 'gemini'
  }

  if (!prompt) return NextResponse.json({ error: 'Prompt required' }, { status: 400 })

  try {
    // ── OPENAI (GPT-image-2) ──────────────────────────────
    if (provider === 'openai') {
      const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY! })

      const fullPrompt = logoImage
        ? (companyName ? `Take this logo for "${companyName}" and ${prompt}` : `Take this logo and ${prompt}`)
        : prompt

      const input: any[] = [{
        role: 'user',
        content: logoImage
          ? [
              { type: 'input_text', text: fullPrompt },
              { type: 'input_image', image_url: logoImage },
            ]
          : [
              { type: 'input_text', text: fullPrompt },
            ],
      }]

      console.log(`[demo] OpenAI generating (gpt-image-2)...`)

      const response = await openai.responses.create({
        model: 'gpt-4.1',
        input,
        tools: [{ type: 'image_generation', model: 'gpt-image-2', size: '1536x1024', quality: 'high' } as any],
      })

      let imageBase64: string | null = null
      for (const output of response.output) {
        if (output.type === 'image_generation_call') {
          imageBase64 = (output as any).result
          break
        }
      }

      if (!imageBase64) {
        let textOutput = ''
        for (const output of response.output) {
          if (output.type === 'message') {
            for (const c of (output as any).content ?? []) {
              if (c.type === 'output_text') textOutput += c.text
            }
          }
        }
        return NextResponse.json({ error: textOutput || 'No image generated by OpenAI' }, { status: 500 })
      }

      return NextResponse.json({ image: `data:image/png;base64,${imageBase64}` })
    }

    // ── GEMINI ──────────────────────────────────────────────
    if (provider === 'gemini') {
      const genai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! })

      const fullPrompt = companyName
        ? `${prompt}\n\nCompany: "${companyName}"`
        : prompt

      const parts: any[] = [{ text: fullPrompt }]
      if (logoImage) {
        const match = logoImage.match(/^data:(image\/\w+);base64,(.+)$/)
        if (match) {
          parts.push({ inlineData: { mimeType: match[1], data: match[2] } })
        }
      }

      console.log(`[demo] Gemini generating (gemini-3-pro-image-preview)...`)

      const response = await genai.models.generateContent({
        model: 'gemini-3-pro-image-preview',
        contents: [{ role: 'user', parts }],
        config: { responseFormat: { image: { aspectRatio: '16:9', imageSize: '4K' } } } as any,
      })

      const responseParts = response.candidates?.[0]?.content?.parts ?? []
      for (const rp of responseParts) {
        if (rp.inlineData) {
          return NextResponse.json({ image: `data:image/png;base64,${rp.inlineData.data}` })
        }
      }

      return NextResponse.json({ error: 'No image generated by Gemini' }, { status: 500 })
    }

    return NextResponse.json({ error: 'Invalid provider' }, { status: 400 })
  } catch (err: any) {
    console.error(`[demo] ${provider} error:`, err)
    return NextResponse.json({ error: err?.message ?? 'Generation failed' }, { status: 500 })
  }
}
